### ISSUE TITLE
Fix the Readme.md file so that is a full description of this task

### ISSUE THREAD

**Issue by HowardCohl** [KChen1250/NIST-DRMF-2015#1]
See https://gist.github.com/jxson/1784669

**Comment by inchkev** [comment]
Done

**Comment by HowardCohl** [comment]
The README.md file doesn't contain a calling sequence for both programs.

**Comment by HowardCohl** [comment]
@KChen1250 

You can model it after:

https://github.com/LibriCerule/NIST-Internship-Algorithms/blob/master/README.md

However, please don't copy verbatim. Give it your own style. Make sure calling sequences for both programs are included.
